// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjs1WfFC_k0BBR9jU2btUoipKQa10hQ4g',
    appId: '1:676581117939:android:f989a30a1bfb53410e0c86',
    messagingSenderId: '676581117939',
    projectId: 'nutri-cal-v1',
    storageBucket: 'nutri-cal-v1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaDdj_ZIXPEfD4QMwm1BCzoCLQYn4odkU',
    appId: '1:676581117939:web:2aa010a3abef55810e0c86',
    messagingSenderId: '676581117939',
    projectId: 'nutri-cal-v1',
    authDomain: 'nutri-cal-v1.firebaseapp.com',
    storageBucket: 'nutri-cal-v1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaDdj_ZIXPEfD4QMwm1BCzoCLQYn4odkU',
    appId: '1:676581117939:web:6319c1571b453c3e0e0c86',
    messagingSenderId: '676581117939',
    projectId: 'nutri-cal-v1',
    authDomain: 'nutri-cal-v1.firebaseapp.com',
    storageBucket: 'nutri-cal-v1.firebasestorage.app',
  );

}